/// Integration tests for Privacy Pool
#[test_only]
module octopus::pool_tests {
    use sui::test_scenario::{Self as ts, Scenario};
    use sui::coin::{Self, Coin};
    use sui::sui::SUI;
    use octopus::pool::{Self, PrivacyPool};

    // Test addresses
    const ADMIN: address = @0xAD;
    const ALICE: address = @0xA11CE;
    const BOB: address = @0xB0B;

    // Test verification key (from unshield circuit compilation)
    // Generated by: node convert_unshield_to_sui.js
    const TEST_VK: vector<u8> = x"e2f26dbea299f5223b646cb1fb33eadb059d9407559d7441dfd902e3a79a4d2dabb73dc17fbc13021e2471e0c08bd67d8401f52b73d6d07483794cad4778180e0c06f33bbc4c79a9cadef253a68084d382f17788f885c9afd176f7cb2f036789edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e198f1ca32b8c078cd1ecfc4a467d8db364b3757d39102fa1ed9255e280333144297c184af83775c6ea998cfb4d59fbd7317b3435e152bace861d478fe0bbcf148f0400000000000000191f71d49c7ecfcc3643957f0d503d24e713cf91937a8a33b7c118a6afef44891ef0fa65bcfbe5a8f6a5a1bb098b6e508467a66a10af02338ce1560ff9609f1588d71006852b8f431fd5d3de34357325e41f3252748926d16c27ed7cb789478068d1e927470885642b8adcd4b38f20583984d85f9274e93b39f834daacf80b0b";

    // Test proof (valid proof for the test input)
    const TEST_PROOF: vector<u8> = x"aca940a9ad7c4beb620beb1b67cd111a2ff32b2f33945bd12cc017c721ec1b91083135faffb3ff4b3cfdcdd0a075154e80b245fa42d14655880096b4ef29fe13f274371b7b8b1d8382f61ba9b61d2901b3557944195ee34771eaee3f0019571cba7b3a4b43ffdd48945edd122d141734a262be4b49e6baf28abeea0c1484050a";

    // Test public inputs (192-byte format, 6 field elements)
    // Format: [nullifiers_hash, change_commitment, recipient_hash, unshield_amount, token, merkle_root]
    // nullifiers_hash:   50c899e811771f3b5b77a50bcde42ab8822a6c8b41b57e4cea8f0c00645da926 (32 bytes, placeholder)
    // change_commitment: 054567511fffb1f0d4a306850419bc74ff3c12d24dbab06b01a454534b625a2a (32 bytes)
    // recipient_hash:    0000000000000000000000000000000000000000000000000000000000000000 (32 bytes, placeholder)
    // unshield_amount:   0046c32300000000000000000000000000000000000000000000000000000000 (32 bytes)
    // token:             075bcd1500000000000000000000000000000000000000000000000000000000 (32 bytes)
    // merkle_root:       2fcfefda413c3b48e0806fb76f38678760d9dc9e23eaecaec3c5c62652982023 (32 bytes, invalid)
    // NOTE: recipient_hash is a placeholder (zeros). Update after circuit recompilation with
    //       the real Poseidon(lo, hi) value for the intended test recipient.
    const TEST_PUBLIC_INPUTS: vector<u8> = x"50c899e811771f3b5b77a50bcde42ab8822a6c8b41b57e4cea8f0c00645da926054567511fffb1f0d4a306850419bc74ff3c12d24dbab06b01a454534b625a2a00000000000000000000000000000000000000000000000000000000000000000046c32300000000000000000000000000000000000000000000000000000000075bcd15000000000000000000000000000000000000000000000000000000002fcfefda413c3b48e0806fb76f38678760d9dc9e23eaecaec3c5c62652982023";

    // Test commitment (from test input generation)
    // commitment = Poseidon(NSK, token, value)
    const TEST_COMMITMENT: vector<u8> = x"589b6f5789efc87da100ca0b91394f7454370d77d4f64569e64bca988b98be2c";

    // Test nullifier
    const TEST_NULLIFIER: vector<u8> = x"50c899e811771f3b5b77a50bcde42ab8822a6c8b41b57e4cea8f0c00645da926";

    // ============ Helper Functions ============

    fun create_test_pool(scenario: &mut Scenario) {
        ts::next_tx(scenario, ADMIN);
        {
            let ctx = ts::ctx(scenario);
            // Note: Using same TEST_VK for both unshield and transfer VKs for now
            // In production, transfer_vk would be generated from transfer.circom
            pool::create_shared_pool<SUI>(TEST_VK, TEST_VK, TEST_VK, ctx);
        };
    }

    fun mint_sui(scenario: &mut Scenario, amount: u64, recipient: address) {
        ts::next_tx(scenario, ADMIN);
        {
            let ctx = ts::ctx(scenario);
            let coin = coin::mint_for_testing<SUI>(amount, ctx);
            transfer::public_transfer(coin, recipient);
        };
    }

    // ============ Tests ============

    #[test]
    fun test_create_pool() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);

        ts::next_tx(&mut scenario, ADMIN);
        {
            let pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);

            // Verify initial state
            assert!(pool::get_balance(&pool) == 0, 0);
            assert!(pool::get_note_count(&pool) == 0, 1);

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    fun test_shield() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);
        mint_sui(&mut scenario, 1_000_000_000, ALICE); // 1 SUI

        // Shield tokens
        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let coin = ts::take_from_sender<Coin<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            pool::shield(
                &mut pool,
                coin,
                TEST_COMMITMENT,
                x"0102030405060708", // Placeholder encrypted note data
                ctx
            );

            // Verify state after shield
            assert!(pool::get_balance(&pool) == 1_000_000_000, 0);
            assert!(pool::get_note_count(&pool) == 1, 1);

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    fun test_multiple_shields() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);
        mint_sui(&mut scenario, 1_000_000_000, ALICE);
        mint_sui(&mut scenario, 2_000_000_000, BOB);

        // Alice shields
        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let coin = ts::take_from_sender<Coin<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            pool::shield(&mut pool, coin, x"0000000000000000000000000000000000000000000000000000000000000001", x"01", ctx);

            assert!(pool::get_balance(&pool) == 1_000_000_000, 0);
            assert!(pool::get_note_count(&pool) == 1, 1);

            ts::return_shared(pool);
        };

        // Bob shields
        ts::next_tx(&mut scenario, BOB);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let coin = ts::take_from_sender<Coin<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            pool::shield(&mut pool, coin, x"0000000000000000000000000000000000000000000000000000000000000002", x"02", ctx);

            assert!(pool::get_balance(&pool) == 3_000_000_000, 0);
            assert!(pool::get_note_count(&pool) == 2, 1);

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    #[expected_failure(abort_code = pool::E_INVALID_ROOT)]
    fun test_unshield_invalid_root() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);
        mint_sui(&mut scenario, 1_000_000_000, ALICE);

        // Shield first (but with different commitment than what proof expects)
        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let coin = ts::take_from_sender<Coin<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            // Shield with a different commitment so the tree root != the root in TEST_PUBLIC_INPUTS
            pool::shield(&mut pool, coin, x"0000000000000000000000000000000000000000000000000000000000000099", x"99", ctx);
            ts::return_shared(pool);
        };

        // Try to unshield - should fail at E_INVALID_ROOT (root check fires after recipient check).
        // We inject BOB's correct recipient_hash so the recipient check passes first,
        // ensuring this test truly reaches and exercises the root validation path.
        ts::next_tx(&mut scenario, BOB);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            // Build public inputs: same as TEST_PUBLIC_INPUTS but with BOB's actual recipient hash
            // at bytes[64..96], so the recipient check passes and the root check is reached.
            // Format: [nullifiers_hash(32), change_commitment(32), recipient_hash(32), unshield_amount(32), token(32), merkle_root(32)]
            let bob_recipient_hash = pool::compute_recipient_hash_for_testing(BOB);
            let mut pi = vector::empty<u8>();
            let mut i = 0u64;
            // Copy nullifiers_hash + change_commitment (bytes 0..64)
            while (i < 64) {
                vector::push_back(&mut pi, *vector::borrow(&TEST_PUBLIC_INPUTS, i));
                i = i + 1;
            };
            // Insert BOB's recipient_hash (bytes 64..96)
            i = 0;
            while (i < 32) {
                vector::push_back(&mut pi, *vector::borrow(&bob_recipient_hash, i));
                i = i + 1;
            };
            // Copy unshield_amount + token + merkle_root (bytes 96..192)
            i = 96;
            while (i < 192) {
                vector::push_back(&mut pi, *vector::borrow(&TEST_PUBLIC_INPUTS, i));
                i = i + 1;
            };

            pool::unshield(
                &mut pool,
                TEST_PROOF,
                pi,
                vector[TEST_NULLIFIER, TEST_NULLIFIER],
                BOB,
                vector::empty<u8>(),
                ctx
            );

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    #[expected_failure(abort_code = pool::E_INVALID_PUBLIC_INPUTS)]
    fun test_unshield_invalid_public_inputs_length() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);

        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            // Try with invalid length public inputs
            pool::unshield(
                &mut pool,
                TEST_PROOF,
                x"0102030405", // Invalid length (5 bytes, should be 192)
                vector[TEST_NULLIFIER, TEST_NULLIFIER], // placeholder nullifiers
                BOB,
                vector::empty<u8>(),
                ctx
            );

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    // Tests that a relayer cannot substitute a different recipient address.
    // TEST_PUBLIC_INPUTS embeds recipient_hash = all zeros (no real address).
    // compute_recipient_hash(BOB) produces a non-zero Poseidon hash, so the
    // assertion fires at step 2 (recipient check) — before the merkle root check —
    // correctly exercising the relayer-substitution prevention path.
    #[test]
    #[expected_failure(abort_code = pool::E_INVALID_PUBLIC_INPUTS)]
    fun test_unshield_wrong_recipient_rejected() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);

        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            // TEST_PUBLIC_INPUTS has recipient_hash = all zeros.
            // BOB's Poseidon hash != zero → recipient check fires → E_INVALID_PUBLIC_INPUTS.
            pool::unshield(
                &mut pool,
                TEST_PROOF,
                TEST_PUBLIC_INPUTS,
                vector[TEST_NULLIFIER, TEST_NULLIFIER],
                BOB,
                vector::empty<u8>(),
                ctx
            );

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    fun test_nullifier_tracking() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);

        ts::next_tx(&mut scenario, ADMIN);
        {
            let pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);

            // Initially nullifier should not be spent
            assert!(!pool::is_nullifier_spent(&pool, TEST_NULLIFIER), 0);

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    fun test_get_merkle_root() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);
        mint_sui(&mut scenario, 1_000_000_000, ALICE);

        // Get initial root
        ts::next_tx(&mut scenario, ADMIN);
        {
            let pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let root1 = pool::get_merkle_root(&pool);
            assert!(vector::length(&root1) == 32, 0);
            ts::return_shared(pool);
        };

        // Shield and verify root changes
        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let coin = ts::take_from_sender<Coin<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            let root_before = pool::get_merkle_root(&pool);
            pool::shield(&mut pool, coin, x"0000000000000000000000000000000000000000000000000000000000000003", x"03", ctx);
            let root_after = pool::get_merkle_root(&pool);

            // Root should change after shield
            assert!(root_before != root_after, 0);

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }

    #[test]
    #[expected_failure(abort_code = 6, location = octopus::pool)] // E_ZERO_AMOUNT
    fun test_shield_zero_amount_fails() {
        let mut scenario = ts::begin(ADMIN);
        create_test_pool(&mut scenario);

        // Try to shield with zero amount
        ts::next_tx(&mut scenario, ALICE);
        {
            let mut pool = ts::take_shared<PrivacyPool<SUI>>(&scenario);
            let ctx = ts::ctx(&mut scenario);

            // Create a coin with zero value
            let zero_coin = coin::mint_for_testing<SUI>(0, ctx);

            // This should fail with E_ZERO_AMOUNT
            pool::shield(
                &mut pool,
                zero_coin,
                TEST_COMMITMENT,
                x"01020304", // Valid hex string with even length
                ctx
            );

            ts::return_shared(pool);
        };

        ts::end(scenario);
    }
}
